/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fromsys;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuan
 */
public class mainGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    public mainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpaneAttendance = new javax.swing.JTabbedPane();
        tabpaneEmployee = new javax.swing.JTabbedPane();
        pnlEmployeeCreate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCreateAddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCreateName = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCreateContact = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCreateEmpStatus = new javax.swing.JTextArea();
        btnCreateEmployee = new javax.swing.JButton();
        pnlEmployeeView = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtblEmployeeView = new javax.swing.JTable();
        btnEmpViewRefresh = new javax.swing.JButton();
        pnlEmployeeUpdate = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtUpdateAddress = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtUpdateId = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtUpdateContact = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtUpdateStatus = new javax.swing.JTextArea();
        btnUpdateEmployee = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtUpdateName = new javax.swing.JTextArea();
        pnlEmployeeDelete = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtDeleteEmployeeId = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnDeleteEmployee = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jtblTimeRecordView = new javax.swing.JTable();
        btnTimeRecordRefresh = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtQrEmployeeName = new javax.swing.JTextArea();
        btnGenerateQr = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtQrOutputName = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblGlobalStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mitemFileExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alphabet | timeMeIn Admin");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(60, 63, 65));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.lightGray);
        setName("Main Frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 500));

        jLabel1.setText("Full Name:");

        jLabel2.setText("Contact Details:");

        jLabel3.setText("Address:");

        jLabel4.setText("Employment Status:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtCreateAddress.setColumns(20);
        txtCreateAddress.setRows(5);
        jScrollPane1.setViewportView(txtCreateAddress);
        txtCreateAddress.getAccessibleContext().setAccessibleName("txtCreateAddress");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtCreateName.setColumns(20);
        txtCreateName.setRows(5);
        jScrollPane2.setViewportView(txtCreateName);
        txtCreateName.getAccessibleContext().setAccessibleName("txtCreateFName");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtCreateContact.setColumns(20);
        txtCreateContact.setRows(5);
        jScrollPane3.setViewportView(txtCreateContact);
        txtCreateContact.getAccessibleContext().setAccessibleName("txtCreateContact");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtCreateEmpStatus.setColumns(20);
        txtCreateEmpStatus.setRows(5);
        jScrollPane4.setViewportView(txtCreateEmpStatus);
        txtCreateEmpStatus.getAccessibleContext().setAccessibleName("txtCreateEmpStatus");

        btnCreateEmployee.setText("Create Employee");
        btnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmployeeCreateLayout = new javax.swing.GroupLayout(pnlEmployeeCreate);
        pnlEmployeeCreate.setLayout(pnlEmployeeCreateLayout);
        pnlEmployeeCreateLayout.setHorizontalGroup(
            pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeCreateLayout.createSequentialGroup()
                .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmployeeCreateLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEmployeeCreateLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmployeeCreateLayout.setVerticalGroup(
            pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeCreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmployeeCreateLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmployeeCreateLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlEmployeeCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tabpaneEmployee.addTab("Create", pnlEmployeeCreate);

        jtblEmployeeView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Address", "Contact", "Employment Status"
            }
        ));
        jScrollPane9.setViewportView(jtblEmployeeView);

        btnEmpViewRefresh.setText("Refresh");
        btnEmpViewRefresh.setMaximumSize(new java.awt.Dimension(127, 25));
        btnEmpViewRefresh.setMinimumSize(new java.awt.Dimension(127, 25));
        btnEmpViewRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpViewRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmployeeViewLayout = new javax.swing.GroupLayout(pnlEmployeeView);
        pnlEmployeeView.setLayout(pnlEmployeeViewLayout);
        pnlEmployeeViewLayout.setHorizontalGroup(
            pnlEmployeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlEmployeeViewLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(btnEmpViewRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmployeeViewLayout.setVerticalGroup(
            pnlEmployeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmpViewRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabpaneEmployee.addTab("View", pnlEmployeeView);

        jLabel6.setText("Full Name:");

        jLabel7.setText("Contact Details:");

        jLabel8.setText("Address:");

        jLabel9.setText("Employment Status:");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtUpdateAddress.setColumns(20);
        txtUpdateAddress.setRows(5);
        jScrollPane5.setViewportView(txtUpdateAddress);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtUpdateId.setColumns(20);
        txtUpdateId.setRows(5);
        jScrollPane6.setViewportView(txtUpdateId);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtUpdateContact.setColumns(20);
        txtUpdateContact.setRows(5);
        jScrollPane7.setViewportView(txtUpdateContact);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtUpdateStatus.setColumns(20);
        txtUpdateStatus.setRows(5);
        jScrollPane8.setViewportView(txtUpdateStatus);

        btnUpdateEmployee.setText("Update Employee");
        btnUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmployeeActionPerformed(evt);
            }
        });

        jLabel10.setText("Employee Id:");

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtUpdateName.setColumns(20);
        txtUpdateName.setRows(5);
        jScrollPane10.setViewportView(txtUpdateName);

        javax.swing.GroupLayout pnlEmployeeUpdateLayout = new javax.swing.GroupLayout(pnlEmployeeUpdate);
        pnlEmployeeUpdate.setLayout(pnlEmployeeUpdateLayout);
        pnlEmployeeUpdateLayout.setHorizontalGroup(
            pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeUpdateLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmployeeUpdateLayout.createSequentialGroup()
                        .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEmployeeUpdateLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmployeeUpdateLayout.setVerticalGroup(
            pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeUpdateLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlEmployeeUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpaneEmployee.addTab("Update", pnlEmployeeUpdate);

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDeleteEmployeeId.setColumns(20);
        txtDeleteEmployeeId.setRows(5);
        jScrollPane11.setViewportView(txtDeleteEmployeeId);

        jLabel11.setText("Employee Id:");

        btnDeleteEmployee.setText("Delete Employee");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmployeeDeleteLayout = new javax.swing.GroupLayout(pnlEmployeeDelete);
        pnlEmployeeDelete.setLayout(pnlEmployeeDeleteLayout);
        pnlEmployeeDeleteLayout.setHorizontalGroup(
            pnlEmployeeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeDeleteLayout.createSequentialGroup()
                .addGroup(pnlEmployeeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmployeeDeleteLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEmployeeDeleteLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmployeeDeleteLayout.setVerticalGroup(
            pnlEmployeeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeDeleteLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnlEmployeeDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        tabpaneEmployee.addTab("Delete", pnlEmployeeDelete);

        tabpaneAttendance.addTab("Employee", tabpaneEmployee);
        tabpaneEmployee.getAccessibleContext().setAccessibleName("Management");

        jtblTimeRecordView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Id", "Employee Id", "Date", "Log in", "Log out", "Total Hours"
            }
        ));
        jScrollPane14.setViewportView(jtblTimeRecordView);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane14)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        jTabbedPane4.addTab("View", jPanel6);

        btnTimeRecordRefresh.setText("Refresh");
        btnTimeRecordRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeRecordRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnTimeRecordRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimeRecordRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpaneAttendance.addTab("Attendance", jPanel4);

        jLabel5.setText("Employee Id:");

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane12.setWheelScrollingEnabled(false);

        txtQrEmployeeName.setColumns(20);
        txtQrEmployeeName.setRows(5);
        jScrollPane12.setViewportView(txtQrEmployeeName);

        btnGenerateQr.setText("Generate QR");
        btnGenerateQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateQrActionPerformed(evt);
            }
        });

        jScrollPane13.setViewportView(txtQrOutputName);

        jLabel12.setText("Output Filename:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnGenerateQr, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateQr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        jTabbedPane3.addTab("Generate", jPanel9);

        tabpaneAttendance.addTab("QR", jTabbedPane3);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblGlobalStatus.setText("Welcome to timeMeIn Admin Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGlobalStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGlobalStatus)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mitemFileExit.setText("Exit");
        mitemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemFileExitActionPerformed(evt);
            }
        });
        jMenu1.add(mitemFileExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabpaneAttendance)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabpaneAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabpaneAttendance.getAccessibleContext().setAccessibleName("Edit");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpViewRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpViewRefreshActionPerformed
        try {
            resultSetToTableModel(EmployeeDao.queryViewAll(), jtblEmployeeView);
        } catch (SQLException objException) {
            lblGlobalStatus.setText("SQLException Error: Check console for more details");
            JOptionPane.showMessageDialog(rootPane,
                                         "SQLException Error: Check console for more details",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
            objException.printStackTrace();
        }
    }//GEN-LAST:event_btnEmpViewRefreshActionPerformed

    private void btnGenerateQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateQrActionPerformed
       Employee tobjEmployee;
       String strQrUuid = txtQrEmployeeName.getText();
       String strFilename = txtQrOutputName.getText();
       txtQrEmployeeName.setText("");
       txtQrOutputName.setText("");
       UUID uuidEmployeeId;
       try {
            uuidEmployeeId = UUID.fromString(strQrUuid);
       } catch (IllegalArgumentException exception) {
            txtQrEmployeeName.setText("");
            txtQrOutputName.setText("");
           lblGlobalStatus.setText("QR Generation Failed: Invalid Employee Id format");
           JOptionPane.showMessageDialog(rootPane,
                                         "QR Generation Failed: Invalid Employee Id format",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
           return;
       }
       int numQueryResult = EmployeeService.getEmployee(uuidEmployeeId).size();
       if (numQueryResult > 0) {
           tobjEmployee = EmployeeService.getEmployee(uuidEmployeeId).get(0);
           EmployeeService.generateQR(uuidEmployeeId, strFilename);
           lblGlobalStatus.setText("QR Generated");
            txtQrEmployeeName.setText("");
            txtQrOutputName.setText("");
       } else {
            txtQrEmployeeName.setText("");
            txtQrOutputName.setText("");
           lblGlobalStatus.setText("QR Generation Failed: Employee Id not found.");
            JOptionPane.showMessageDialog(rootPane,
                                         "QR Generation Failed: Employee Id not found.",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnGenerateQrActionPerformed

    private void btnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeActionPerformed
       String strFormName = txtCreateName.getText();
       String strFormAddress = txtCreateAddress.getText();
       String strFormContact = txtCreateContact.getText();
       String strFormStatus = txtCreateEmpStatus.getText();
       EmployeeService.createEmployee(strFormName, strFormAddress,
                                      strFormContact, strFormStatus);
       lblGlobalStatus.setText("Employee data created");
       txtCreateName.setText("");
       txtCreateAddress.setText("");
       txtCreateContact.setText("");
       txtCreateEmpStatus.setText("");
    }//GEN-LAST:event_btnCreateEmployeeActionPerformed

    private void btnTimeRecordRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeRecordRefreshActionPerformed
        try {
            resultSetToTableModel(AttendanceRecordDao.queryViewAll(), jtblTimeRecordView);
        } catch (SQLException objException) {
            lblGlobalStatus.setText("SQLException Error: Check console for more details");
            JOptionPane.showMessageDialog(rootPane,
                                         "SQLException Error: Check console for more details",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
            objException.printStackTrace();
        }
    }//GEN-LAST:event_btnTimeRecordRefreshActionPerformed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        String strEmployeeId = txtDeleteEmployeeId.getText();
        UUID uuidEmployeeId;
        try {
            uuidEmployeeId = UUID.fromString(strEmployeeId);
        } catch (IllegalArgumentException exception) {
            txtDeleteEmployeeId.setText("");
            lblGlobalStatus.setText("Employee Deletion Failed: Invalid Employee Id format");
            JOptionPane.showMessageDialog(rootPane,
                                         "Employee Deletion Failed: Invalid Employee Id format",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
            return;
        }
        int numQueryResult = EmployeeService.getEmployee(uuidEmployeeId).size();
        if (numQueryResult > 0) {
            EmployeeService.deleteEmployee(uuidEmployeeId);
            lblGlobalStatus.setText("Employee data deleted");
            txtDeleteEmployeeId.setText("");
        } else {
            txtDeleteEmployeeId.setText("");
            lblGlobalStatus.setText("Employee Deletion Failed: Employee Id not found");
            JOptionPane.showMessageDialog(rootPane,
                                         "Employee Deletion Failed: Employee Id not found",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void btnUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmployeeActionPerformed
        String strUpdateId = txtUpdateId.getText();
        UUID uuidEmployeeId;
        String strUpdateName = txtUpdateName.getText();
        String strUpdateAddress = txtUpdateAddress.getText();
        String strUpdateContact = txtUpdateContact.getText();
        String strUpdateStatus = txtUpdateStatus.getText();
        try {
            uuidEmployeeId = UUID.fromString(strUpdateId);
        } catch (IllegalArgumentException exception) {
            txtUpdateId.setText("");
            txtUpdateName.setText("");
            txtUpdateAddress.setText("");
            txtUpdateContact.setText("");
            txtUpdateStatus.setText("");
            lblGlobalStatus.setText("Employee Update Failed: Invalid Employee Id format");
            JOptionPane.showMessageDialog(rootPane,
                                         "Employee Update Failed: Invalid Employee Id format",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
           return;
        }
        int numQueryResult = EmployeeService.getEmployee(uuidEmployeeId).size();
        if (numQueryResult > 0) {
            lblGlobalStatus.setText("Employee data updated");
            EmployeeService.updateEmployee(uuidEmployeeId, strUpdateName,
                                           strUpdateAddress, strUpdateContact,
                                           strUpdateStatus);
            txtUpdateId.setText("");
            txtUpdateName.setText("");
            txtUpdateAddress.setText("");
            txtUpdateContact.setText("");
            txtUpdateStatus.setText("");
        } else {
            txtUpdateId.setText("");
            txtUpdateName.setText("");
            txtUpdateAddress.setText("");
            txtUpdateContact.setText("");
            txtUpdateStatus.setText("");
            lblGlobalStatus.setText("Employee Update Failed: Employee id not found");
            JOptionPane.showMessageDialog(rootPane,
                                         "Employee Update Failed: Employee id not found",
                                         "Error",
                                         JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUpdateEmployeeActionPerformed

    private void mitemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitemFileExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Alphabet Inc | timeMeIn\n2022 All rights Reserved.");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // View Updater
    public void resultSetToTableModel(ResultSet tResultSet, JTable tTable) throws SQLException{
        //Create new table model
        DefaultTableModel tableModel = new DefaultTableModel();

        //Retrieve meta data from ResultSet
        ResultSetMetaData metaData = tResultSet.getMetaData();

        //Get number of columns from meta data
        int columnCount = metaData.getColumnCount();

        //Get all column names from meta data and add columns to table model
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++){
            tableModel.addColumn(metaData.getColumnLabel(columnIndex));
        }

        //Create array of Objects with size of column count from meta data
        Object[] objArrRow = new Object[columnCount];

        //Scroll
        while (tResultSet.next()){
            //Get object from column with specific index of result set to array of objects
            for (int i = 0; i < columnCount; i++){
                objArrRow[i] = tResultSet.getObject(i+1);
            }
            //Now add row to table model with that array of objects as an argument
            tableModel.addRow(objArrRow);
        }
        
        tTable.setModel(tableModel);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEmployee;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnEmpViewRefresh;
    private javax.swing.JButton btnGenerateQr;
    private javax.swing.JButton btnTimeRecordRefresh;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jtblEmployeeView;
    private javax.swing.JTable jtblTimeRecordView;
    private javax.swing.JLabel lblGlobalStatus;
    private javax.swing.JMenuItem mitemFileExit;
    private javax.swing.JPanel pnlEmployeeCreate;
    private javax.swing.JPanel pnlEmployeeDelete;
    private javax.swing.JPanel pnlEmployeeUpdate;
    private javax.swing.JPanel pnlEmployeeView;
    private javax.swing.JTabbedPane tabpaneAttendance;
    private javax.swing.JTabbedPane tabpaneEmployee;
    private javax.swing.JTextArea txtCreateAddress;
    private javax.swing.JTextArea txtCreateContact;
    private javax.swing.JTextArea txtCreateEmpStatus;
    private javax.swing.JTextArea txtCreateName;
    private javax.swing.JTextArea txtDeleteEmployeeId;
    private javax.swing.JTextArea txtQrEmployeeName;
    private javax.swing.JTextPane txtQrOutputName;
    private javax.swing.JTextArea txtUpdateAddress;
    private javax.swing.JTextArea txtUpdateContact;
    private javax.swing.JTextArea txtUpdateId;
    private javax.swing.JTextArea txtUpdateName;
    private javax.swing.JTextArea txtUpdateStatus;
    // End of variables declaration//GEN-END:variables
}
